get_team_names <- function() {
	team_names <- matrix('',nrow=0,ncol=2)

	team_names <- rbind(team_names, c('ATL', 'Atlanta Hawks'))
	team_names <- rbind(team_names, c('BKN', 'Brooklyn Nets'))
	team_names <- rbind(team_names, c('BOS', 'Boston Celtics'))
	team_names <- rbind(team_names, c('CHA', 'Charlotte Hornets'))
	team_names <- rbind(team_names, c('CHI', 'Chicago Bulls'))
	team_names <- rbind(team_names, c('CLE', 'Cleveland Cavaliers'))
	team_names <- rbind(team_names, c('DAL', 'Dallas Mavericks'))
	team_names <- rbind(team_names, c('DEN', 'Denver Nuggets'))
	team_names <- rbind(team_names, c('DET', 'Detroit Pistons'))
	team_names <- rbind(team_names, c('GSW', 'Golden State Warriors'))
	team_names <- rbind(team_names, c('HOU', 'Houston Rockets'))
	team_names <- rbind(team_names, c('IND', 'Indiana Pacers'))
	team_names <- rbind(team_names, c('LAC', 'Los Angeles Clippers'))
	team_names <- rbind(team_names, c('LAL', 'Los Angeles Lakers'))
	team_names <- rbind(team_names, c('MEM', 'Memphis Grizzlies'))
	team_names <- rbind(team_names, c('MIA', 'Miami Heat'))
	team_names <- rbind(team_names, c('MIL', 'Milwaukee Bucks'))
	team_names <- rbind(team_names, c('MIN', 'Minnesota Timberwolves'))
	team_names <- rbind(team_names, c('NOP', 'New Orleans Pelicans'))
	team_names <- rbind(team_names, c('NYK', 'New York Knicks'))
	team_names <- rbind(team_names, c('OKC', 'Oklahoma City Thunder'))
	team_names <- rbind(team_names, c('ORL', 'Orlando Magic'))
	team_names <- rbind(team_names, c('PHI', 'Philadelphia 76ers'))
	team_names <- rbind(team_names, c('PHX', 'Phoenix Suns'))
	team_names <- rbind(team_names, c('POR', 'Portland Trail Blazers'))
	team_names <- rbind(team_names, c('SAC', 'Sacramento Kings'))
	team_names <- rbind(team_names, c('SAS', 'San Antonio Spurs'))
	team_names <- rbind(team_names, c('TOR', 'Toronto Raptors'))
	team_names <- rbind(team_names, c('UTA', 'Utah Jazz'))
	team_names <- rbind(team_names, c('WAS', 'Washington Wizards'))

	team_names <- as.data.frame(team_names, stringsAsFactors=FALSE)
	colnames(team_names) <- c('abbrev','name')

	return(team_names)
}